# Generated by Django 5.2.5 on 2025-08-18 02:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_address_order_shipping_order_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='SC para Stripe Card, PP para PayPal, TR para transferencia PSE, CA para Cash', max_length=10, unique=True)),
                ('label', models.CharField(help_text='Stripe Card para key SC, PayPal para key PP, Transferencia PSE para key TR, Cash para key CA', max_length=50)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Icon payment image')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Completado'), ('F', 'Fallido'), ('R', 'Reembolsado'), ('X', 'Cancelado')], db_index=True, default='P', help_text='Estado del pago.', max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto total del pago.', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Moneda del pago.', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que el pago fue confirmado.', null=True)),
                ('stripe_session_id', models.CharField(blank=True, db_index=True, help_text='ID de sesión de Stripe (checkout).', max_length=255, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, help_text='ID de PaymentIntent de Stripe.', max_length=255, null=True)),
                ('paypal_transaction_id', models.CharField(blank=True, db_index=True, help_text='ID de transacción de PayPal.', max_length=255, null=True)),
                ('external_reference', models.CharField(blank=True, db_index=True, help_text='Referencia externa del pago (ej: número de recibo, referencia bancaria).', max_length=100, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Monto de impuestos incluidos en el pago.', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Monto de descuentos aplicados al pago.', max_digits=10)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error devuelto por el gateway, si aplica.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales del pago (gateway, cliente, etc.).')),
                ('email_sent', models.BooleanField(default=False, help_text='Indica si se ha enviado un correo electrónico de confirmación del pago.')),
                ('order', models.ForeignKey(help_text='Pedido asociado a este pago.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('user', models.ForeignKey(help_text='Usuario que realiza el pago.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(help_text='Método de pago utilizado.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentmethod')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('stripe_refund_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paypal_refund_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('refunded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paypal_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('CANCELED', 'Cancelada'), ('PAST_DUE', 'Vencida'), ('UNPAID', 'No pagada'), ('INCOMPLETE', 'Incompleta'), ('TRIALING', 'En prueba')], default='INCOMPLETE', max_length=20)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payments.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='payments_pa_payment_33e537_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_payment_intent_id'], name='payments_pa_stripe__6fe52c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paypal_transaction_id'], name='payments_pa_paypal__b9e2c0_idx'),
        ),
    ]
