# Generated by Django 5.2.1 on 2025-05-20 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
