# Generated by Django 5.2.1 on 2025-05-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_subscriptionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('SC', 'Stripe Card'), ('PP', 'PayPal'), ('TR', 'PSE Transfer')], default='SC', max_length=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('F', 'Failed'), ('R', 'Refunded')], default='P', max_length=1),
        ),
    ]
