# Generated by Django 5.2.1 on 2025-05-25 07:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_currency'),
        ('payments', '0008_alter_payment_payment_option_alter_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='stripe_payment_method_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_price_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='USD', help_text='Moneda del pago.', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto de descuentos aplicados al pago.', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='error_message',
            field=models.TextField(blank=True, help_text='Mensaje de error devuelto por el gateway, si aplica.', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='external_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia externa del pago (ej: número de recibo, referencia bancaria).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Datos adicionales del pago (gateway, cliente, etc.).'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el pago fue confirmado.', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID de transacción de PayPal.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID de PaymentIntent de Stripe.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto de impuestos incluidos en el pago.', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario que realiza el pago.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='gateway_payment_method_id',
            field=models.CharField(blank=True, help_text='ID en el gateway.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='refund',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='refund',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='paypal_refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='refunded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Monto total del pago.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(help_text='Pedido asociado a este pago.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('SC', 'Tarjeta Stripe'), ('PP', 'PayPal'), ('TR', 'Transferencia PSE'), ('CA', 'Efectivo'), ('OT', 'Otro')], default='SC', help_text='Método de pago utilizado.', max_length=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Completado'), ('F', 'Fallido'), ('R', 'Reembolsado'), ('X', 'Cancelado')], db_index=True, default='P', help_text='Estado del pago.', max_length=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID de sesión de Stripe (checkout).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='stripe_refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activa'), ('CANCELED', 'Cancelada'), ('PAST_DUE', 'Vencida'), ('UNPAID', 'No pagada'), ('INCOMPLETE', 'Incompleta'), ('TRIALING', 'En prueba')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_option'], name='payments_pa_payment_76ee6e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_payment_intent_id'], name='payments_pa_stripe__6fe52c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paypal_transaction_id'], name='payments_pa_paypal__b9e2c0_idx'),
        ),
    ]
