# Generated by Django 5.2.1 on 2025-05-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('SC', 'Tarjeta Stripe'), ('PP', 'PayPal'), ('TR', 'Transferencia PSE'), ('CA', 'Efectivo')], default='SC', help_text='Método de pago utilizado.', max_length=2),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
