# Generated by Django 5.2.1 on 2025-05-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='alt_text',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Icon payment image'),
        ),
    ]
