# Generated by Django 5.2.1 on 2025-06-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_remove_paymentmethod_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Indica si se ha enviado un correo electrónico de confirmación del pago.'),
        ),
    ]
