# Generated by Django 5.2.6 on 2025-09-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='license',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Store License'),
        ),
    ]
