# Generated by Django 5.2.6 on 2025-09-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='/default_avatar.png', null=True, upload_to='', verbose_name='Profile Photo'),
        ),
    ]
