# Generated by Django 5.0.2 on 2024-02-28 17:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='/profile_default.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
