# Generated by Django 5.0.2 on 2024-02-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='/default_avatar_qs2vrz', null=True, upload_to='', verbose_name='Profile Photo'),
        ),
    ]
