# Generated by Django 5.1.1 on 2024-10-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='/profile_default.png', null=True, upload_to='', verbose_name='Profile Photo'),
        ),
    ]
