# Generated by Django 5.1.1 on 2025-02-03 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
