# Generated by Django 5.1.1 on 2025-02-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='/avatar.png', null=True, upload_to='', verbose_name='Profile Photo'),
        ),
    ]
