# Generated by Django 5.2.6 on 2025-09-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', help_text='Customer ID from Stripe payment system', max_length=100, verbose_name='Stripe Customer ID'),
        ),
    ]
