# Generated by Django 5.2.1 on 2025-05-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_address_default_address_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Customer ID from Stripe payment system', max_length=100, null=True, verbose_name='Stripe Customer ID'),
        ),
    ]
