# Generated by Django manually

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        # No operations needed as common only contains abstract models
    ]
