# Generated by Django 5.0.2 on 2024-06-08 04:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_is_parent_category_parent'),
        ('coupons', '0002_remove_coupon_content_type'),
        ('inventory', '0003_alter_inventory_published_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_type', models.CharField(choices=[('Amount', 'amount'), ('Rate', 'rate')], default='rate', max_length=6)),
                ('discount_rate', models.IntegerField(blank=True, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_purchased_items', models.IntegerField()),
                ('apply_to', models.CharField(choices=[('Product', 'product'), ('Category', 'category')], default='product', max_length=8)),
                ('target_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('target_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
