# Generated by Django 5.2.1 on 2025-06-04 08:49

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_is_parent_category_parent'),
        ('coupons', '0003_campaign'),
        ('inventory', '0007_rename_taxes_inventory_taxe'),
        ('orders', '0017_order_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
        migrations.AddField(
            model_name='coupon',
            name='apply_to',
            field=models.CharField(choices=[('ALL', 'All Products'), ('CATEGORY', 'Specific Categories'), ('PRODUCT', 'Specific Products')], default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='can_combine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(blank=True, to='categories.category'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 4, 8, 49, 10, 741623, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='coupon',
            name='first_purchase_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_uses',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_uses_per_user',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(blank=True, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='used_by',
            field=models.ManyToManyField(related_name='used_coupons', through='coupons.CouponUsage', to=settings.AUTH_USER_MODEL),
        ),
    ]
