# Generated by Django 5.2.1 on 2025-06-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_remove_coupon_inventory_remove_coupon_user_and_more'),
    ]

    operations = [
    ]
