# Generated by Django 5.2.1 on 2025-06-12 00:31

import coupons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_populate_coupon_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(default=coupons.models.get_default_end_date),
        ),
    ]
