# Generated by Django 5.2.1 on 2025-06-15 22:41

import coupons.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_alter_coupon_code_alter_coupon_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=coupons.fields.UpperCaseCharField(max_length=255, unique=True),
        ),
    ]
