# Generated by Django 5.2.1 on 2025-06-04 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0008_alter_coupon_code_alter_coupon_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 4, 9, 19, 46, 557819, tzinfo=datetime.timezone.utc)),
        ),
    ]
