# Generated by Django 5.2.1 on 2025-06-09 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0010_alter_coupon_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 9, 19, 38, 21, 349630, tzinfo=datetime.timezone.utc)),
        ),
    ]
