# Generated by Django 5.2.1 on 2025-06-10 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0011_alter_coupon_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 10, 1, 29, 21, 721896, tzinfo=datetime.timezone.utc)),
        ),
    ]
