# Generated by Django 5.2.1 on 2025-06-11 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0018_alter_coupon_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 11, 2, 28, 56, 823946, tzinfo=datetime.timezone.utc)),
        ),
    ]
