# Generated by Django 5.0 on 2024-01-11 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
        ('ratings', '0005_alter_rating_unique_together_rating_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_review', to='profiles.profile', verbose_name='Agent being rated'),
        ),
    ]
