# Generated by Django 5.0 on 2024-01-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_alter_rating_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='agent',
        ),
    ]
