# Generated by Django 5.0 on 2024-01-24 21:49

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='inventory',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='published_status',
            field=models.BooleanField(default=False, verbose_name='Published Status'),
        ),
    ]
