# Generated by Django 5.0.2 on 2024-02-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
