# Generated by Django 5.0 on 2024-01-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_managers_alter_product_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='sku',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='upc',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
