# Generated by Django 5.0.1 on 2024-02-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='type',
            name='type_attributes',
        ),
        migrations.AddField(
            model_name='inventory',
            name='attribute_values',
            field=models.ManyToManyField(related_name='prod_attribute', to='inventory.attributevalue'),
        ),
        migrations.AddField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
