# Generated by Django 5.0.2 on 2024-02-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measureunit',
            name='description',
            field=models.CharField(default='Units', max_length=50, unique=True, verbose_name='Descripción'),
        ),
    ]
