# Generated by Django 5.0.2 on 2024-02-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_is_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_parent',
        ),
        migrations.AddField(
            model_name='category',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
