# Generated by Django 5.0 on 2024-01-24 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_sku_alter_inventory_upc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='last_checked',
        ),
    ]
