# Generated by Django 5.0.1 on 2024-02-05 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stock_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalues',
            name='attributevalues',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_attributevalues', to='inventory.attributevalue'),
        ),
        migrations.AlterField(
            model_name='attributevalues',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_inventory_attributevalues', to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='media',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_media', to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='typeattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_type_attribute', to='inventory.attribute'),
        ),
        migrations.AlterField(
            model_name='typeattribute',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_type', to='inventory.type'),
        ),
    ]
