# Generated by Django 5.0.1 on 2024-01-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ('created_at',), 'verbose_name': 'inventory image', 'verbose_name_plural': 'inventory images'},
        ),
        migrations.RemoveField(
            model_name='media',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='media',
            name='is_feature',
        ),
        migrations.AddField(
            model_name='media',
            name='default',
            field=models.BooleanField(default=False, help_text='format: default=false, true=default image', verbose_name='por defecto'),
        ),
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.ImageField(default='images/default.png', help_text='format: required, default-default.png', upload_to='images/', verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='media',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='format: default=false, true=default image', verbose_name='destacado'),
        ),
        migrations.AlterField(
            model_name='media',
            name='alt_text',
            field=models.CharField(help_text='format: required, max-255', max_length=255, verbose_name='texto alternativo'),
        ),
    ]
