# Generated by Django 5.0.2 on 2024-02-12 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_product_is_parent_category_is_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='measure_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MeasureUnit', to='inventory.measureunit', verbose_name='Measure Unit'),
        ),
    ]
