# Generated by Django 5.0.1 on 2024-02-06 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_attributevalues_attributevalues_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='published_status',
        ),
    ]
