# Generated by Django 5.1.1 on 2024-10-11 18:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_media_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.19'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='store_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
