# Generated by Django 5.0.1 on 2024-02-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_inventory_published_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='published_status',
            field=models.BooleanField(default=False, verbose_name='Published Status'),
        ),
    ]
