# Generated by Django 5.1.1 on 2024-10-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventory_taxes_alter_inventory_store_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='taxes',
            new_name='taxe',
        ),
    ]
