# Generated by Django 5.2.5 on 2025-08-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measureunit',
            name='is_custom',
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='description',
            field=models.CharField(choices=[('Units', 'Units'), ('Grams', 'Grams'), ('Pounds', 'Pounds'), ('Kilograms', 'Kilograms'), ('Mililiters', 'Mililiters'), ('Liters', 'Liters'), ('Other', 'Other')], default='Units', max_length=50, unique=True, verbose_name='Descripción'),
        ),
    ]
