# Generated by Django 5.2.5 on 2025-08-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_is_parent_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='measureunit',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='Indica si es una unidad de medida personalizada creada por el usuario', verbose_name='Es personalizada'),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='description',
            field=models.CharField(max_length=100, unique=True, verbose_name='Descripción'),
        ),
    ]
