# Generated by Django 5.2.6 on 2025-09-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Comment'),
        ),
    ]
