# Generated by Django 5.0.2 on 2024-02-11 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsonpromotion',
            old_name='inventory_id',
            new_name='product_inventory_id',
        ),
        migrations.AlterUniqueTogether(
            name='productsonpromotion',
            unique_together={('product_inventory_id', 'promotion_id')},
        ),
    ]
