# Generated by Django 5.0.2 on 2024-02-09 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventory_attribute_and_more'),
        ('promotion', '0002_rename_inventory_id_productsonpromotion_product_inventory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsonpromotion',
            name='product_inventory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ProductInventoryOnPromotion', to='inventory.inventory'),
        ),
    ]
