# Generated by Django 5.0.2 on 2024-04-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_count_cartitem_quantity'),
        ('inventory', '0003_alter_inventory_published_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_items',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='cart.CartItem', to='inventory.inventory'),
        ),
    ]
