# Generated by Django 5.0.2 on 2024-06-08 04:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_deliverycost'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycost',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
