# Generated by Django 5.0.2 on 2024-06-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_deliverycost_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycost',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
