# Generated by Django 5.1.1 on 2024-11-07 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_cartitem_cart'),
        ('inventory', '0007_rename_taxes_inventory_taxe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_inventory', to='inventory.inventory'),
        ),
    ]
