# Generated by Django 5.1.1 on 2025-04-07 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_alter_cartitem_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created_at']},
        ),
    ]
