# Generated by Django 5.2.3 on 2025-07-04 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_cart_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='coupon',
        ),
    ]
