# Generated by Django 5.2.3 on 2025-07-04 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_remove_cartitem_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
    ]
