# Generated by Django 5.2.3 on 2025-07-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_cart_coupon'),
        ('coupons', '0007_alter_coupon_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
        migrations.AddField(
            model_name='cart',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='coupons.coupon'),
        ),
    ]
