# Generated by Django 5.2.5 on 2025-08-18 01:28

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipping",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("time_to_delivery", models.CharField(max_length=255)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("NACIONAL", "Nacional"),
                            ("INTERNACIONAL", "Internacional"),
                            ("EXPRESS", "Express"),
                            ("ESPECIAL", "Especial"),
                        ],
                        default="NACIONAL",
                        max_length=50,
                    ),
                ),
                (
                    "transport_type",
                    models.CharField(
                        choices=[("TERRESTRE", "Terrestre"), ("AEREO", "Aéreo")],
                        default="TERRESTRE",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Marcar como método de envío predeterminado",
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        help_text="Monto mínimo para envío gratuito",
                        max_digits=10,
                    ),
                ),
                (
                    "standard_shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3.00"),
                        help_text="Costo estándar de envío",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping",
                "verbose_name_plural": "Shipping",
            },
        ),
    ]
