# Generated by Django 5.2.1 on 2025-05-30 17:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='free_shipping_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Monto mínimo para envío gratuito', max_digits=10),
        ),
        migrations.AddField(
            model_name='shipping',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='service_type',
            field=models.CharField(choices=[('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional'), ('EXPRESS', 'Express'), ('ESPECIAL', 'Especial')], default='NACIONAL', max_length=50),
        ),
        migrations.AddField(
            model_name='shipping',
            name='standard_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Costo estándar de envío', max_digits=10),
        ),
        migrations.AddField(
            model_name='shipping',
            name='transport_type',
            field=models.CharField(choices=[('TERRESTRE', 'Terrestre'), ('AEREO', 'Aéreo')], default='TERRESTRE', max_length=50),
        ),
    ]
