# Generated by Django 5.2.1 on 2025-05-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shipping_free_shipping_threshold_shipping_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Campo obsoleto. Usar standard_shipping_cost en su lugar.', max_digits=5),
        ),
    ]
