# Generated by Django 5.2.1 on 2025-05-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_alter_shipping_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='price',
        ),
    ]
