# Generated by Django 5.2.1 on 2025-06-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_remove_shipping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Marcar como método de envío predeterminado'),
        ),
    ]
