# Generated by Django 5.1.1 on 2025-01-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_date_issued'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_issued',
        ),
    ]
