# Generated by Django 5.0 on 2024-01-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_cover_photo_alter_product_photo1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_photo',
            field=models.ImageField(blank=True, default='/house_sample.jpg', null=True, upload_to='Econline-img', verbose_name='Main Photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo1',
            field=models.ImageField(blank=True, default='/interior_sample.jpg', null=True, upload_to='Econline-img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo2',
            field=models.ImageField(blank=True, default='/interior_sample.jpg', null=True, upload_to='Econline-img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo3',
            field=models.ImageField(blank=True, default='/interior_sample.jpg', null=True, upload_to='Econline-img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo4',
            field=models.ImageField(blank=True, default='/interior_sample.jpg', null=True, upload_to='Econline-img'),
        ),
    ]
