# Generated by Django 5.0 on 2024-01-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published_status',
            field=models.BooleanField(default=True, verbose_name='Pub Status'),
        ),
    ]
